import { Inter } from "next/font/google";
import Link from 'next/link';
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-[#0A0A2E] p-4 fixed w-full top-0 z-50">
          <Link href="/" className="text-white mr-4">Home</Link>
          <Link href="/dashboard" className="text-white hover:text-pink-500">Dashboard</Link>
        </nav>
        <main className="mt-16">
          {children}
        </main>
      </body>
    </html>
  );
}